#!/bin/sh
# Regression: every public fn in `lib/*.cyr` must carry a doc comment
# immediately before its `fn name(...)` line. Pinned 2026-04-27 after
# the v5.7.20 lib/json.cyr ship surfaced 28 undocumented fns in CI
# (the GitHub Actions `doc / Doc coverage (stdlib)` job failed; locally
# the gap was invisible because nothing in `scripts/check.sh` ran the
# walk).
#
# Mirror of the CI workflow's doc-coverage walk:
#   for f in lib/*.cyr (skip symlinks + cyrius-distlib bundles):
#     ./build/cyrdoc --check "$f" → "N undocumented"
#   total += N; assert total == 0.
#
# Cyrdoc walks the AST and looks for a `# comment` on the line
# IMMEDIATELY before each `fn name(...)`. Block-header decorations
# (`# === Constructors ===`) don't satisfy the per-fn requirement.
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CYRDOC="$ROOT/build/cyrdoc"
if [ ! -x "$CYRDOC" ]; then
    echo "  skip: $CYRDOC not built (cat programs/cyrdoc.cyr | build/cc5 > build/cyrdoc)"
    exit 0
fi

total=0
worst=""
worst_n=0

for f in "$ROOT"/lib/*.cyr; do
    [ -f "$f" ] || continue
    [ -L "$f" ] && continue
    # Skip distlib bundles (auto-generated; their original fns live in
    # the source repo and are documented there).
    head -n 5 "$f" 2>/dev/null | grep -q "^# Generated by: cyrius distlib$" && continue

    u=$("$CYRDOC" --check "$f" 2>&1 | tail -1 | grep -oE '[0-9]+ undocumented' | grep -oE '^[0-9]+' || echo 0)
    [ -z "$u" ] && u=0
    if [ "$u" -gt 0 ]; then
        total=$((total + u))
        if [ "$u" -gt "$worst_n" ]; then
            worst_n="$u"
            worst="$(basename "$f")"
        fi
    fi
done

if [ "$total" -gt 0 ]; then
    echo "  FAIL: $total undocumented public fns across lib/*.cyr"
    if [ -n "$worst" ]; then
        echo "    worst offender: $worst ($worst_n undocumented)"
        echo "    detail: $CYRDOC --check $ROOT/lib/$worst 2>&1 | grep undocumented"
    fi
    exit 1
fi

echo "  PASS: lib/*.cyr doc coverage (0 undocumented)"
exit 0
