#!/bin/sh
# cyrius-header — generate C header from Cyrius source
# Scans for `pub fn` declarations and emits C prototypes.
# All Cyrius types are i64 (int64_t in C).
#
# Usage: cyrius header lib/str.cyr > str.h
#        cyrius header --all lib/*.cyr > cyrius.h

if [ -z "$1" ]; then
    echo "Usage: cyrius header [--all] <file.cyr> [file2.cyr ...]"
    exit 1
fi

guard="CYRIUS_FFI_H"
if [ "$1" = "--all" ]; then
    shift
    guard="CYRIUS_ALL_H"
fi

echo "/* Auto-generated by cyrius header — do not edit */"
echo "#ifndef ${guard}"
echo "#define ${guard}"
echo ""
echo "#include <stdint.h>"
echo ""
echo "/* All Cyrius values are 64-bit integers */"
echo "typedef int64_t cyr_val;"
echo ""

for file in "$@"; do
    name=$(basename "$file" .cyr)
    echo "/* --- ${name} --- */"
    grep '^pub fn ' "$file" | while IFS= read -r line; do
        fname=$(echo "$line" | sed 's/^pub fn //;s/(.*//;s/ .*//')
        raw=$(echo "$line" | sed 's/.*(\([^)]*\)).*/\1/')
        if [ -z "$raw" ] || [ "$raw" = "$line" ]; then
            echo "cyr_val ${fname}(void);"
        else
            pcount=$(echo "$raw" | awk -F, '{print NF}')
            proto="cyr_val ${fname}("
            pi=1
            while [ $pi -le $pcount ]; do
                pname=$(echo "$raw" | cut -d, -f$pi | tr -d ' ' | sed 's/:.*//')
                if [ $pi -gt 1 ]; then proto="${proto}, "; fi
                proto="${proto}cyr_val ${pname}"
                pi=$((pi + 1))
            done
            echo "${proto});"
        fi
    done
    echo ""
done

echo "#endif /* ${guard} */"
